### ISSUE TITLE
Support properties on createSpatialIndex.srid attribute

### ISSUE THREAD

**Issue by jmvivo** [lonnyj/liquibase-spatial#3]
On http://lonnyj.github.io/liquibase-spatial/liquibase-spatial.xsd the createSpatialIndex srid attribute is declared as integer:

    <xsd:attributeGroup name="createSpatialIndex">
        <xsd:annotation>
        
        
        <xsd:attribute name="srid" type="xsd:integer"/>

So, I get a parse exception when I try something like this:

    <spatial:createSpatialIndex tableName="kp"
          indexName="ix_kp_geometry"
          geometryType="Point" srid="${pom.base-crs}">
      <column name="geometry" />
    </spatial:createSpatialIndex>

**Comment by jmvivo** [comment]
Any news about this?. Thanks

**Comment by lonnyj** [comment]
Yes!  I reproduced the problem.  I'm going to update the XSD to allow for a string then add validation to the Change to ensure that the contents are numeric.  I'll try to fix that this weekend.

**Comment by jmvivo** [comment]
Brilliant!! Thank you very much.

**Comment by lonnyj** [comment]
This issue was fixed in versions 1.0.2, 1.1.1 and 1.2.1.

**Comment by jmvivo** [comment]
Thanks!!
